# Generated by Django 5.1.2 on 2024-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkelement',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Укажите уровень иерархии', verbose_name='Уровень иерархии'),
        ),
    ]
