# Generated by Django 5.1.2 on 2024-10-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_networkelement_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название', max_length=128, verbose_name='Название')),
                ('email', models.EmailField(help_text='Укажите email', max_length=254, unique=True, verbose_name='Email')),
                ('model', models.CharField(blank=True, help_text='Укажите модель продукта', max_length=100, null=True, verbose_name='Модель продукта')),
                ('released_at', models.DateTimeField(auto_now_add=True, help_text='Укажите дату выхода продукта на рынок', verbose_name='Дата выхода продукта на рынок')),
                ('seller', models.ForeignKey(blank=True, help_text='Укажите продавца', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='network.networkelement', verbose_name='Продавец')),
            ],
        ),
    ]
