# Generated by Django 5.1.2 on 2024-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='Укажите дату выхода продукта на рынок', null=True, verbose_name='Дата выхода продукта на рынок'),
        ),
    ]
