# Generated by Django 5.1.2 on 2024-10-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='released_at',
            field=models.DateField(blank=True, help_text='Укажите дату выхода продукта на рынок', null=True, verbose_name='Дата выхода продукта на рынок'),
        ),
    ]
